server:
  port: 6688 #服务端口

spring: 
  application:  
    name: springcloud_config  #指定服务名--->现在没有用,后面讲此服务注册到eureka统一管理的时候,作为唯一标识符
  cloud:  
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/Gegow/{application}-xxx
          username: Gegow
          password: Lyh163752
#          search-paths: dir,dir*  如：加载根目录、dir目录、dir开头的目录下的配置文件。
#          clone-on-start: true  设置Config Server启动时是否克隆git仓库。
logging:
  level:
    org.springframework.boot: debug
    org.springframework.cloud: debug
eureka.client.serviceUrl.defaultZone: "http://localhost:1001/eureka"